export default [
    {
      id: 0,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 1,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 2,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 3,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 4,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 5,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
      id: 6,
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
      SKU: 1,
      name: 'Cocktail',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
      price: 25,
    },
    {
        id: 0,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 1,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 2,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 3,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 4,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 5,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 6,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 0,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 1,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 2,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 3,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 4,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 5,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 6,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 0,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 1,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 2,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 3,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 4,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 5,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      },
      {
        id: 6,
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=986&q=80',
        SKU: 1,
        name: 'Cocktail',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis varius dui ut gravida. Integer vitae sodales tellus. Fusce euismod dolor et volutpat viverra. ',
        price: 25,
      }
  ]